language: node_js
node_js:
- '6'
before_script:
- npm install -g gulp
script: gulp
deploy:
  provider: heroku
  api_key:
    secure: nR0EEe/VT+hydy0KuoTtoBbzGnMLYw9blgzEftD20fF37oG0E9toieRwVvNDyB04C8h8L5bW4L1dDWA61XN6fmqzYTrXDzym0VmVCQDpELysoyqyF8eWq9vfLngvssmlfO0TcpCtgCkGlHQ8eF0wLMC57U7bYK3iirSrKqYk4GFIKLIWwc2baDLdE9SoJ4WJcZu8mU+7S91Npddr6wdh+J1pwFbnYp36c+ZJ8s+v/omur6Z9acrmL0zH0BtRnrLX7sRIKH5STVRd5Wz5qNwjJU3bGG4nytm0z5kSK721JkEtq/N4bR4crx8GhADvMoaT4jypKXantdw40jFSumFqp0JHiQVm+m2oS+zhKaPmUqdMIFCJ8EdJWDbetrIvbHvvDxPqKeTGbskPhIawIc/6EakBxdnSvGSRJFq0TtArD3b8xjuspAytelTFVk2Wcwugu5YIN7ijdFdVABN4ilk/nZeEG4nfTkKU5ifXVdeia0BFfTnu55GuUqyuauNW+cV1FGa8ly1My0SkYCLZEwTo0rFNEMRp1EesF+DDsc7Cpx3pbobEnGyaTQ1T9JfvQUwXOejhBW+OZOcMZ5t3mtAQ5ZrUDkZ1OsQtdq5lai9RK8s/pSQxb23qfkLxkSUkINpKKLovFsiZU5I3qD6ddLWTtIAGSESStZtu15/Ro611CTw=
  app: tbd-app
  on:
    repo: tee-bee-dee/tbd-app
